name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sample-job-1:
      runs-on: ubuntu-latest
      steps:
          - name: step-1
            run: echo "${NUGET_CUSTOMFEEDPASSWORD}"

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --build-arg Nuget_PasswordArg=${env.NUGET_CUSTOMFEEDPASSWORD} --file Dockerfile --tag my-image-name:$(date +%s) 
