name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t advisorapi:latest . --build-arg Nuget_PasswordArg=${{secrets.NUGET_CUSTOMFEEDPASSWORD}} --file Dockerfile --tag my-image-name:$(date +%s) 

  compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: isbang/compose-action@v0.1
        with:
         compose-file: './AdvisorApi/docker/docker-compose.yml'
  
  newman:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - uses: matt-ball/newman-action@master
          with:
            collection: Postman/AddvisorApi.postman_collection.json
            environment: My Workspace.postman_globals.json
