name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome. This is your first issue. Contact:"" if you have any questions.'
        pr-message: 'Welcome. This is your first Pull Request. Contact:"" if you have any questions.'
