name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine

    steps:
    - run: apk update
    - run: apk upgrade
    - run: apk --no-cache add --update git openssh
    - uses: actions/checkout@v2
    - run: dotnet restore
    - run: dotnet build
    - run: dotnet test --no-build -c debug /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
